Add logic to handle if branch already exists (#126)
* Add the 'dev-dependencies' in make's 'generate-docs'

* add "poetry run"

* add comment

* comment

* remove space

* add make clean and seperate commands

* add git checkout -B

* typo

* add check if branch existed

diff --git a/.github/workflows/python-client-gen.yml b/.github/workflows/python-client-gen.yml
--- a/.github/workflows/python-client-gen.yml
+++ b/.github/workflows/python-client-gen.yml
@@ -6,6 +6,10 @@ on:
         description: 'The short commit sha that triggered the workflow'
         required: true
         type: string
+
+env:
+  NEW_BRANCH: openapi-${{ github.event.inputs.openapi_short_sha }}/clientgen
+
 jobs:
   Generate-Python-Client:
     runs-on: ubuntu-latest
@@ -28,7 +32,7 @@ jobs:
         path: ./DigitalOcean-public.v2.yaml
 
     - name: Checkout new Branch
-      run: git checkout -b openapi-${{ github.event.inputs.openapi_short_sha }}/clientgen
+      run:  git checkout -b ${{ env.NEW_BRANCH }} 
       env:
         GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
 
@@ -46,16 +50,29 @@ jobs:
     - name: Generate Python client documentation
       run: make generate-docs
     - name: Add and commit changes
+      id: add-commit-changes
+      continue-on-error: true
       run: |
         git config --global user.email "api-engineering@digitalocean.com"
         git config --global user.name "API Engineering"
         git add .
-        git commit -m "[bot] Updated client based on openapi/${{ github.event.inputs.openapi_short_sha }}"
-        git push --set-upstream origin ${{ github.event.inputs.openapi_short_sha }}
+        git commit -m "[bot] Updated client based on ${{ env.NEW_BRANCH }}"
+        git push --set-upstream origin ${{ env.NEW_BRANCH }}
       env:
         GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
 
+    - name: Check if branch existed
+      # If steps.create-pr was anything but successful, it's possible that
+      # the branch was created in previous pipeline runs so it should be manually deleted.
+      if: steps.add-commit-changes.outcome != 'success'
+      run: |
+        echo "Add and commit changes step failed. It's possible the branch ${{ env.NEW_BRANCH }} already existed. Please delete the branch and re-run the pipeline."
+        exit 1
+
     - name: Create Pull Request
-      run: gh pr create --title "[bot] Re-Generate w/ digitalocean/openapi ${{ github.event.inputs.openapi_short_sha }}" --body "Regenerate python client with the commit,${{ github.event.inputs.openapi_short_sha }}, pushed to digitalocean/openapi. Owners must review to confirm if integration/mocked tests need to be added to the client to reflect the changes." --head "openapi_trigger_${{ github.event.inputs.openapi_short_sha }}" -r owners
+      id: create-pr
+      if: steps.add-commit-changes.outcome == 'success'
+      continue-on-error: true
+      run: gh pr create --title "[bot] Re-Generate w/ digitalocean/openapi ${{ github.event.inputs.openapi_short_sha }}" --body "Regenerate python client with the commit, [${{ github.event.inputs.openapi_short_sha }}](https://github.com/digitalocean/openapi/commit/${{ github.event.inputs.openapi_short_sha }}) , pushed to digitalocean/openapi. Owners must review to confirm if integration/mocked tests need to be added to the client to reflect the changes." --head "${{ env.NEW_BRANCH }}" -r digitalocean/api-cli
       env:
-        GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+        GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}  
