add check if branch existed

diff --git a/.github/workflows/python-client-gen.yml b/.github/workflows/python-client-gen.yml
--- a/.github/workflows/python-client-gen.yml
+++ b/.github/workflows/python-client-gen.yml
@@ -32,7 +32,7 @@ jobs:
         path: ./DigitalOcean-public.v2.yaml
 
     - name: Checkout new Branch
-      run: git checkout -B ${{ env.NEW_BRANCH }} #If -B is given, <new-branch> is created if it doesn’t exist; otherwise, it is reset. 
+      run:  git checkout -b ${{ env.NEW_BRANCH }} 
       env:
         GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
 
@@ -61,10 +61,18 @@ jobs:
       env:
         GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
 
+    - name: Check if branch existed
+      # If steps.create-pr was anything but successful, it's possible that
+      # the branch was created in previous pipeline runs so it should be manually deleted.
+      if: steps.add-commit-changes.outcome != 'success'
+      run: |
+        echo "Add and commit changes step failed. It's possible the branch ${{ env.NEW_BRANCH }} already existed. Please delete the branch and re-run the pipeline."
+        exit 1
+
     - name: Create Pull Request
       id: create-pr
       if: steps.add-commit-changes.outcome == 'success'
       continue-on-error: true
       run: gh pr create --title "[bot] Re-Generate w/ digitalocean/openapi ${{ github.event.inputs.openapi_short_sha }}" --body "Regenerate python client with the commit, [${{ github.event.inputs.openapi_short_sha }}](https://github.com/digitalocean/openapi/commit/${{ github.event.inputs.openapi_short_sha }}) , pushed to digitalocean/openapi. Owners must review to confirm if integration/mocked tests need to be added to the client to reflect the changes." --head "${{ env.NEW_BRANCH }}" -r digitalocean/api-cli
       env:
-        GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+        GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}  
